### PR TITLE
Fix #16 - weird scope errors are fixed

### LINKED ISSUE #16: Scope errors
It looks like the change in #12 have borked our scope with `this`. We are running into this error on [line 19](https://github.com/codeforamerica/wand/blob/master/src/js/wand.js#L19):

```
TypeError: undefined is not an object (evaluating 'this.nodes.length')
```

### PR DESCRIPTION
**Pull request by ErnieAtLYD**

### CODE REVIEW

**Comment by mapsam** [comment]
Yay no scope issues!

One thing to keep in mind as we move forward: if we remove the `new` keyword and stop using `prototype` we are effectively losing the ability to build "plugins" that require access to the Wand functions, such as `renderNode()`. I'd love to look at how to properly build in a plugin architecture at some point, using a faked out `Class` system - but that's down the road I think. Not entirely sure if any of this matters right now... just a thought!

**Comment by bsmithgall** [comment]
@creade would love to hear your thoughts on ^

**Comment by mapsam** [comment]
@creade and I are going to talk about this Nonsense That I Speak Of this afternoon and we will return with our thoughts!

**Comment by mapsam** [comment]
Crossing fingers ...

**Comment by mapsam** [comment]
Yay! @creade with some good scoping work here. I think this is done - and we've got an example of how add/update functions to the library via a plugin. 

Onward :point_right:

File: src/js/wand.js [hunk 1]
```diff
@@ -1,24 +1,31 @@
...
+
+  var wand = {};
+
+  var options = {},
+      nodes = [],
+      elem = null;
+
+  var badHtmlError = new Error('You did not pass a valid HTML Element');
+
+  wand.init = function(opts) {
```
Comment (bsmithgall) [inline src/js/wand.js:11]: If possible, I'd like to be able to run the `init` method when you create a new `Wand`. I'm thinking of something like [`datatables`](http://www.datatables.net/) or [`bootstrap-datepicker`](https://bootstrap-datepicker.readthedocs.org/en/latest/) where you don't have to call an explicit initialization method, but just instead do something like 

```
$('#myDatepicker').datepicker()
```

**Comment by bsmithgall** [comment]
:+1: for the pattern and the article @mapsam referenced

File: src/js/wand.js (hunk 1 above)
Comment (mapsam) [inline src/js/wand.js:11]: I agree that would be nice. @creade and I went in a lot of circles this afternoon, and I can't remember if we nixed the idea for a reason or because we just didn't get that far. Maybe he can remember? @creade?

Comment (bsmithgall) [inline src/js/wand.js:11]: bump @creade

Comment (mapsam) [inline src/js/wand.js:11]: :facepunch: @creade !!!!! :point_right: :facepunch:

Comment (ErnieAtLYD) [inline src/js/wand.js:11]: @creade 

hqdefault
